title: Spectre Intelligence Blog
description: slaeryan's blog - some rants about Information Security and random stuff
show_downloads: false
show_repo: false
google_analytics: UA-162044832-1
theme: jekyll-theme-hacker
